import turtle


def letter_A():
    turtle.left(70)
    turtle.forward(187)
    turtle.right(140)
    turtle.forward(93.5)
    turtle.right(110)
    turtle.forward(65)
    turtle.right(180)
    turtle.forward(65)
    turtle.right(70)
    turtle.forward(93.5)
    turtle.penup()
    turtle.left(70)
    turtle.forward(10)
    turtle.pendown()


def letter_B():
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(45)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(70)
    turtle.right(180)
    turtle.forward(70)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(77)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(180)
    turtle.penup()
    turtle.forward(105)
    turtle.left(90)
    turtle.forward(150)
    turtle.pendown()


def letter_C():
    turtle.penup()
    turtle.forward(150)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(80)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(80)
    turtle.right(45)
    turtle.forward(100)
    turtle.penup()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(160)
    turtle.left(90)
    turtle.pendown()


def letter_D():
    turtle.left(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(45)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(100)
    turtle.right(45)
    turtle.forward(40)
    turtle.right(45)
    turtle.forward(70)
    turtle.penup()
    turtle.right(180)
    turtle.forward(150)
    turtle.pendown()


def letter_E():
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(75)
    turtle.penup()
    turtle.forward(50)
    turtle.pendown()


def letter_F():
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(75)
    turtle.left(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(125)
    turtle.pendown()


def letter_G():
    turtle.penup()
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(180)
    turtle.pendown()
    turtle.forward(70)
    turtle.left(45)
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(60)
    turtle.left(45)
    turtle.forward(30)
    turtle.left(45)
    turtle.forward(70)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(20)
    turtle.left(45)
    turtle.forward(40)
    turtle.penup()
    turtle.right(180)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()


def letter_H():
    turtle.left(90)
    turtle.forward(100)
    turtle.penup()
    turtle.right(90)
    turtle.forward(75)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)
    turtle.pendown()


def letter_I():
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(75)
    turtle.right(90)
    turtle.penup()
    turtle.forward(100)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(75)
    turtle.right(180)
    turtle.forward(37.5)
    turtle.left(90)
    turtle.forward(100)
    turtle.penup()
    turtle.left(90)
    turtle.forward(87.5)


def letter_J():
    turtle.penup()
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(100)
    turtle.left(180)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(80)
    turtle.right(45)
    turtle.forward(30)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(20)
    turtle.right(45)
    turtle.forward(40)
    turtle.penup()
    turtle.right(90)
    turtle.forward(150)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.pendown()

turtle.mainloop()

