import turtle
def write_u():
    turtle.right(90)
    turtle.forward(50)
    turtle.circle(30,180,20)
    turtle.forward(50)
    turtle.penup()
    turtle.right(90)
    turtle.forward(10)
    turtle.pendown()
def write_v():
    turtle.right(75)
    turtle.forward(115)
    turtle.right(215)
    turtle.forward(115)
    turtle.penup()
    turtle.right(70)
    turtle.forward(10)
    turtle.pendown()
def write_w():
    turtle.right(75)
    turtle.forward(115)
    turtle.right(215)
    turtle.forward(60)
    turtle.left(45)
    turtle.backward(60)
    turtle.left(325)
    turtle.forward(115)
    turtle.penup()
    turtle.right(85)
    turtle.forward(10)
    turtle.pendown()
def write_x():
    turtle.right(45)
    turtle.forward(140)
    turtle.backward(70)
    turtle.penup()
    turtle.left(90)
    turtle.forward(70)
    turtle.pendown()
    turtle.backward(140)
    turtle.penup()
    turtle.forward(140)
    turtle.right(45)
    turtle.forward(10)
    turtle.pendown()
def write_y():
    turtle.right(50)
    turtle.forward(40)
    turtle.left(110)
    turtle.forward(40)
    turtle.penup()
    turtle.backward(40)
    turtle.left(30)
    turtle.pendown()
    turtle.backward(50)
    turtle.penup()
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(83)
    turtle.right(90)
    turtle.pendown()
    
    
def write_z():
    turtle.forward(100)
    turtle.left(45)
    turtle.backward(140)
    turtle.right(45)
    turtle.forward(100)
    turtle.penup()
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(10)
    turtle.pendown()
